/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javafx.scene.control.RadioButton;

/**
 *
 * @author student
 */
public class data_view extends javax.swing.JFrame {

    /**
     * Creates new form data_view
     */
    String typ;
    public data_view() {
        initComponents();
    }
    
    public data_view(String s)
    {
       initComponents();
       typ =s;
       if(s.equals("EMPLOYEEDB"))
       {
           jRadioButton3.setVisible(false);
           jRadioButton1.setEnabled(true);
           jLabel1.setText("EMPLOYEE ID");
           jLabel2.setText("NAME");
           jLabel3.setText("SALARY");
           jLabel4.setText("POST");
       }
        if(s.equals("REGISTERED"))
       {
           jRadioButton3.setVisible(false);
           jRadioButton1.setVisible(false);
           jRadioButton1.setEnabled(true);
           jLabel1.setText("CUSTOMER ID");
           jLabel2.setText("NAME");
           jLabel3.setVisible(false);
           jLabel4.setVisible(false);
           jTextField3.setVisible(false);
           jTextField4.setVisible(false);
       }
        if(s.equals("TRACK"))
       {
           jRadioButton2.setVisible(false);
           jRadioButton1.setVisible(false);
           jLabel1.setText("BOOKING ID");
           jLabel2.setText("SET STATUS");
           jLabel3.setVisible(false);
           jLabel4.setVisible(false);
           jTextField3.setVisible(false);
           jTextField4.setVisible(false);
       }
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jDialog1 = new javax.swing.JDialog();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jRadioButton3 = new javax.swing.JRadioButton();
        jButton3 = new javax.swing.JButton();

        jDialog1.setMinimumSize(new java.awt.Dimension(405, 300));
        jDialog1.setResizable(false);
        jDialog1.setSize(new java.awt.Dimension(405, 300));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setText("Operation Successful!");

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog1Layout.createSequentialGroup()
                .addContainerGap(73, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(jLabel8)
                .addContainerGap(145, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(782, 550));
        setMinimumSize(new java.awt.Dimension(782, 550));
        setPreferredSize(new java.awt.Dimension(782, 550));
        setResizable(false);
        setSize(new java.awt.Dimension(782, 550));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("ENTRY FIELD 1: ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(23, 358, 116, 17);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("ENTRY FIELD 1: ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(23, 401, 116, 17);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("ENTRY FIELD 1: ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(23, 446, 116, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("ENTRY FIELD 1: ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(23, 494, 116, 17);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(23, 313, 749, 2);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRadioButton1.setText("Add Item");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(565, 105, 91, 25);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRadioButton2.setText("Delete Item");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(565, 133, 107, 25);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("PERFORM OPERATION");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(459, 197, 313, 33);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Selection area:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(459, 30, 90, 15);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/rsz_vdr.png"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(23, 30, 373, 200);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Enter item data:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(23, 321, 100, 15);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(212, 359, 380, 17);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(211, 401, 380, 20);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(211, 446, 380, 20);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(217, 494, 374, 20);

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRadioButton3.setText("Update Item");
        getContentPane().add(jRadioButton3);
        jRadioButton3.setBounds(565, 77, 113, 25);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("BACK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(620, 406, 116, 45);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
         jLabel1.setVisible(true);
        jLabel2.setVisible(true);
         jLabel3.setVisible(true);
        jLabel4.setVisible(true);
        jTextField1.setVisible(true);
        jTextField2.setVisible(true);
        jTextField3.setVisible(true);
        jTextField4.setVisible(true);
        
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        admin_options ao = new admin_options();
        ao.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
       jLabel1.setVisible(true);
        jLabel2.setVisible(true);
        jTextField1.setVisible(true);
        jTextField2.setVisible(true);
        jLabel3.setVisible(false);
        jLabel4.setVisible(false);
        jTextField3.setVisible(false);
         jTextField4.setVisible(false);
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       if(jRadioButton1.isSelected())
       {
           try{
                    
                    
                    Class.forName("oracle.jdbc.driver.OracleDriver");
                    Connection conn= DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","system","ddas123");
                    PreparedStatement ps = conn.prepareStatement("insert into employeedb values('"+jTextField1.getText()+"','"+jTextField2.getText()+"','"+jTextField3.getText()+"','"+jTextField4.getText()+"')");
                    ResultSet rs = null;
                    rs = ps.executeQuery();
                    jDialog1.setVisible(true);
                    jTextField1.setText("");
                    jTextField2.setText("");
                    jTextField3.setText("");
                    jTextField4.setText("");
        }
        catch(Exception e)
        {
           System.out.println(e);  
        }
       }
       
       if(jRadioButton2.isSelected())
       {
           if(typ.equals("EMPLOYEEDB"))
           {try
               {
                    
                    
                    Class.forName("oracle.jdbc.driver.OracleDriver");
                    Connection conn= DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","system","ddas123");
                    PreparedStatement ps = conn.prepareStatement("delete from employeedb where empid = '"+jTextField1.getText()+"' and ename = '"+jTextField2.getText()+"'");
                    ResultSet rs = null;
                    rs = ps.executeQuery();
                    jDialog1.setVisible(true);
                    jTextField1.setText("");
                    jTextField2.setText("");
                }
        catch(Exception e)
        {
            System.out.println(e);
        }}
        
        if(typ.equals("REGISTERED"))
        {
            try{
                    
                    
                    Class.forName("oracle.jdbc.driver.OracleDriver");
                    Connection conn= DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","system","ddas123");
                    PreparedStatement ps = conn.prepareStatement("delete from registered where cust_id = '"+jTextField1.getText()+"' and name = '"+jTextField2.getText()+"'");
                    ResultSet rs = null;
                    rs = ps.executeQuery();
                    jDialog1.setVisible(true);
                    jTextField1.setText("");
                    jTextField2.setText("");
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
            
        }
           
       }
       
       if(jRadioButton3.isSelected())
       {
           try{
                    
                    
                    Class.forName("oracle.jdbc.driver.OracleDriver");
                    Connection conn= DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","system","ddas123");
                    PreparedStatement ps = conn.prepareStatement("update track set status = '"+jTextField2.getText()+"' where book_id = '"+jTextField1.getText()+"'");
                    ResultSet rs = null;
                    rs = ps.executeQuery();
                    jDialog1.setVisible(true);
                    jTextField1.setText("");
                    jTextField2.setText("");
                    jTextField3.setText("");
                    jTextField4.setText("");
        }
        catch(Exception e)
        {
           System.out.println(e);  
        }
       }

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(data_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(data_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(data_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(data_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new data_view().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
