/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package project;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

/**
 *
 * @author deblin
 */
public class details extends javax.swing.JFrame {

    /** Creates new form details */
    String id, nam, phn, eml, car,book_id,k3;
    int units;
    public details() {
        initComponents();
    }
    public details(String s1, String s2, String s4, String s5, String s6 ) {
        initComponents();
        jTextField1.setText(s2);
        jTextField3.setText(s1);
        jTextField4.setText("PROCESSING");
        id = s2;
        nam = s4;
        phn = s5;
        eml = s6;
        car = s1;
    }
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        jDialog1.setMinimumSize(new java.awt.Dimension(612, 360));
        jDialog1.setResizable(false);
        jDialog1.setSize(new java.awt.Dimension(612, 360));
        jDialog1.getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("     Congratulations! You're order has been placed successfully.");
        jDialog1.getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 11, 577, 32);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("BOOKING IDENTIFICATION NUMBER:");
        jDialog1.getContentPane().add(jLabel5);
        jLabel5.setBounds(32, 80, 271, 17);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("STATUS:");
        jDialog1.getContentPane().add(jLabel6);
        jLabel6.setBounds(32, 136, 61, 17);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("EXPECTED DELIVERY:");
        jDialog1.getContentPane().add(jLabel7);
        jLabel7.setBounds(32, 192, 156, 17);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("PICK-UP SHOWROOM ADDRESS:");
        jDialog1.getContentPane().add(jLabel8);
        jLabel8.setBounds(32, 248, 230, 17);

        jTextField2.setEditable(false);
        jTextField2.setText("Delivery pending");
        jDialog1.getContentPane().add(jTextField2);
        jTextField2.setBounds(350, 140, 110, 20);

        jTextField5.setText("30th April, 2018");
        jDialog1.getContentPane().add(jTextField5);
        jTextField5.setBounds(350, 190, 100, 20);

        jTextField6.setText("VDR Showroom, Manipal, India, 576104");
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        jDialog1.getContentPane().add(jTextField6);
        jTextField6.setBounds(347, 248, 240, 20);

        jTextField7.setEditable(false);
        jDialog1.getContentPane().add(jTextField7);
        jTextField7.setBounds(347, 80, 240, 20);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("LOGOUT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jDialog1.getContentPane().add(jButton3);
        jButton3.setBounds(241, 286, 120, 30);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/backnew.png"))); // NOI18N
        jDialog1.getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 0, 610, 340);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(782, 540));
        setMinimumSize(new java.awt.Dimension(782, 540));
        setPreferredSize(new java.awt.Dimension(782, 540));
        setSize(new java.awt.Dimension(782, 540));
        getContentPane().setLayout(null);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("CONFIRM");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(609, 451, 120, 40);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(51, 451, 100, 40);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("CUSTOMER IDENTIFICATION NUMBER:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(51, 123, 281, 17);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("VEHICLE SELECTED:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(51, 212, 146, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("STATUS:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(51, 305, 61, 17);

        jTextField1.setEditable(false);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(428, 123, 301, 20);

        jTextField3.setEditable(false);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(428, 212, 301, 20);

        jTextField4.setEditable(false);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(428, 305, 301, 20);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/green_back.png"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(0, 0, 780, 530);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        prd_listing p = new prd_listing(id, nam, phn, eml);
        p.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        login n = new login();
        n.setVisible(true);
        jDialog1.setVisible(false);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String name[] = car.split(" "); 
        int c = 0;
        try{
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection conn= DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","system","ddas123");
            PreparedStatement ps = conn.prepareStatement("select * from track where car_name = '"+car+"'");
            ResultSet rs = null;
            rs = ps.executeQuery();
                while(rs.next())
                {
                    c++;
                }
            //System.out.println(c);  
            }
        catch(Exception e){}
       
        book_id = "vdr"+name[name.length -1]+"#"+id+"_"+c;
        
        try{
                    
                    
                    Class.forName("oracle.jdbc.driver.OracleDriver");
                    Connection conn= DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","system","ddas123");
                    PreparedStatement ps = conn.prepareStatement("insert into track values('"+id+"','"+book_id+"','"+car+"','Not Delivered')");
                    ResultSet rs = null;
                    rs = ps.executeQuery();
        }
        catch(Exception e){}
        
        try{  
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection conn= DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","system","ddas123");
            PreparedStatement ps = conn.prepareStatement("select units_sold from sales where car_name = '"+car+"'");
            ResultSet rs = null;
            rs = ps.executeQuery();
            if(rs.next())
            {
                k3 = rs.getString("units_sold");
                units = Integer.parseInt(k3);
                units = units+1;
                k3 = ""+units;
            }
        }
        catch(Exception e){}
        
        try{
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection conn= DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","system","ddas123");
            PreparedStatement ps = conn.prepareStatement("update sales set units_sold = '"+k3+"' where car_name = '"+car+"'");
            ResultSet rs = null;
            rs = ps.executeQuery();
        }
        catch(Exception e){}     
        jDialog1.setVisible(true);
        jTextField7.setText(book_id);
         
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new details().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables

}
