/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.*;
/**
 *
 * @author student
 */
public class prd_listing extends javax.swing.JFrame {

    /**
     * Creates new form prd_listing
     */
    String s = "";
    String id, name, phn, eml;
    String nam; 
    String mil; 
    String seat;
    String cost; 
    String type; 
    public prd_listing() {
        initComponents();
        assignp();
    }
    public prd_listing(String s1, String s2, String s3, String s4) {
        initComponents();
        assignp();
        id = s1;
        name = s2;
        phn = s3;
        eml = s4;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PRODUCT LISTING");
        setMaximumSize(new java.awt.Dimension(782, 530));
        setMinimumSize(new java.awt.Dimension(782, 530));
        setPreferredSize(new java.awt.Dimension(782, 530));
        setResizable(false);
        setSize(new java.awt.Dimension(782, 530));
        getContentPane().setLayout(null);

        jComboBox1.setMaximumRowCount(11);
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NONE", "HONDA CITY", "HONDA WR-V", "HYUNDAI ELANTRA", "HYUNDAI VERNA", "MARUTI SUZUKI ALTO K10", "MARUTI SUZUKI BALENO", "MARUTI SUZUKI SWIFT", "MARUTI SUZUKI VITARA BREZZA", "SKODA OCTAVIA", "TOYOTA INNOVA CRYSTA", " " }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(210, 90, 373, 41);

        jLabel1.setFont(new java.awt.Font("MS Reference Sans Serif", 3, 24)); // NOI18N
        jLabel1.setText("                             OUR CATALOGUE......");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 11, 762, 71);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/rsz_vdr.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(210, 180, 373, 200);

        jButton1.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jButton1.setText("PROCEED TO BOOKING");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(210, 430, 373, 44);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/back_list.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 780, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    static String image[] = {"baleno.png", "brezza.png", "city.png", "elantra.png", "innova_crysta.png", "k10.png", "octavia.png", "swift.png", "verna.png", "wrv.png", "rsz_vdr.png"};
    ImageIcon[] img = new ImageIcon[11];
    void assignp(){
        for(int c = 0; c < image.length; c++){
            img[c] = new ImageIcon(getClass().getResource("/project/ang/"+image[c]));
        }
    }
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        s = jComboBox1.getSelectedItem().toString();
        switch(s)
        {
            
            case "HONDA CITY":
                jLabel2.setIcon(img[2]);
                break;
            case "HONDA WR-V":
                jLabel2.setIcon(img[9]);
                break;
            case "HYUNDAI ELANTRA":
                jLabel2.setIcon(img[3]);
                break;
            case "HYUNDAI VERNA":
                jLabel2.setIcon(img[8]);
                break;
            case "MARUTI SUZUKI ALTO K10":
                jLabel2.setIcon(img[5]);
                break;
            case "MARUTI SUZUKI BALENO":
                jLabel2.setIcon(img[0]);
                break;
            case "MARUTI SUZUKI SWIFT":
                jLabel2.setIcon(img[7]);
                break;
            case "MARUTI SUZUKI VITARA BREZZA":
                jLabel2.setIcon(img[1]);
                break;
            case "SKODA OCTAVIA":
                jLabel2.setIcon(img[6]);
                break;
            case "TOYOTA INNOVA CRYSTA":
                jLabel2.setIcon(img[4]);
                break;
            default:
                jLabel2.setIcon(img[10]);
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection conn= DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","system","ddas123");
            PreparedStatement ps = conn.prepareStatement("select * from car1 where cname='"+s+"'");
            ResultSet rs = null;
            rs = ps.executeQuery();
            if(rs.next())
            {
                nam = rs.getString("cname");
                mil = rs.getString("mileage");
                seat = rs.getString("seat");
                cost = rs.getString("cost");
                type = rs.getString("type");   
            }   
        }
        catch(Exception e){ }
        switch(s)
        {
            case "HONDA CITY":
                car4_gallery c4 = new car4_gallery(nam,mil,cost,seat,type, id, name, phn, eml);
                c4.setVisible(true);
                this.setVisible(false);
                break;
            case "HONDA WR-V":
                car10_gallery c10 = new car10_gallery(nam,mil,cost,seat,type, id, name, phn, eml);
                c10.setVisible(true);
                this.setVisible(false);
                break;
            case "HYUNDAI ELANTRA":
                car3_gallery c3 = new car3_gallery(nam,mil,cost,seat,type, id, name, phn, eml);
                c3.setVisible(true);
                this.setVisible(false);
                break;
            case "HYUNDAI VERNA":
                car9_gallery c9 = new car9_gallery(nam,mil,cost,seat,type, id, name, phn, eml);
                c9.setVisible(true);
                this.setVisible(false);
                break;
            case "MARUTI SUZUKI ALTO K10":
                car6_gallery c6 = new car6_gallery(nam,mil,cost,seat,type, id, name, phn, eml);
                c6.setVisible(true);
                this.setVisible(false);
                break;
            case "MARUTI SUZUKI BALENO":
                car2_gallery c2 = new car2_gallery(nam,mil,cost,seat,type, id, name, phn, eml);
                c2.setVisible(true);
                this.setVisible(false);
                break;
            case "MARUTI SUZUKI SWIFT":
                car8_gallery c8 = new car8_gallery(nam,mil,cost,seat,type, id, name, phn, eml);
                c8.setVisible(true);
                this.setVisible(false);
                break; 
            case "MARUTI SUZUKI VITARA BREZZA":
                car1_gallery c1 = new car1_gallery(nam,mil,cost,seat,type, id, name, phn, eml);
                c1.setVisible(true);
                this.setVisible(false);
                break;
            case "SKODA OCTAVIA":
                car7_gallery c7 = new car7_gallery(nam,mil,cost,seat,type, id, name, phn, eml);
                c7.setVisible(true);
                this.setVisible(false);
                break;
            case "TOYOTA INNOVA CRYSTA":
                car5_gallery c5 = new car5_gallery(nam,mil,cost,seat,type, id, name, phn, eml);
                c5.setVisible(true);
                this.setVisible(false);
                break;
            default:
                System.out.println("ENDED!!!");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(prd_listing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(prd_listing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(prd_listing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(prd_listing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                prd_listing prd = new prd_listing();
                prd.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
